const state = {
  db: {
    products: [],
    users: [],
    reviews: [],
    branches: [],
    promos: [],
    settings: {},
  },
  session: {
    sb: null,
    dbOk: false,
    currentUser: null,
    selectedBranch: null,
    wishlist: JSON.parse(localStorage.getItem('wl') || '[]'),
  },
  editor: {
    product: null,
    user: null,
    branch: null,
    socialBranch: null,
    promo: null,
    tab: 'info',
    promoCropper: null,
    promoCropBlob: null,
  },
  catalog: {
    activeFilter: 'Semua',
    page: 1,
    showAll: false,
    showAllFeat: false,
    showAllNewest: false,
    exploreTab: 'featured',
    exploreExpanded: false,
    viewMode: 'grid',
    searchTimer: null,
    dashCatFilter: 'Semua',
  },
  admin: {
    panel: 'dashboard',
    productPage: 1,
    userPage: 1,
    branchPage: 1,
    sortField: 'name',
    sortDir: 'asc',
    activityLog: [],
    reviewPage: 1,
    reviewFilterStatus: 'all',
    reviewFilterRating: 0,
    reviewSelected: [],
    sideLock: false,
  },
  ui: {
    uploading: false,
    revRating: 5,
    revPhotos: [],
    submittingReview: false,
    confirmRes: null,
    detailSlide: {
      timer: null,
      idx: 0,
      imgs: [],
      paused: false,
    },
    zoom: {
      scale: 1,
      zooming: false,
      startDist: 0,
      startScale: 1,
    },
    revGalleryPhotos: null,
    revGalleryIdx: -1,
    ticker: { timer: null, idx: 0, },
  },
};
const TIMEOUTS = {
  FALLBACK: 7000,
  PING: 4000,
  FULL_LOAD: 8000,
};